# Generated by Django 5.2.8 on 2026-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Google', 'Google'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Hoco', 'Hoco')])),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('icon_class', models.CharField(blank=True, default='nothing', null=True)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Google', 'Google'), ('Xiaomi', 'Xiaomi'), ('OnePlus', 'OnePlus'), ('Hoco', 'Hoco')])),
                ('short', models.CharField()),
                ('camera', models.CharField()),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
